---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r libraries, include = FALSE}
library(tidyverse)
library(lubridate)
library(chron)
library(sp)
library(raster)
library(ggplot2)
library(leaflet)
library(rgeos)
library(rgdal)
library(sf)
library(tmap)
```

```{r Explore}
unique(Test$Activity)
unique(Test$Activity_other)

### This is being done quickly for the purposes of plot - double check no comments misinterpreted
### eg. Tant sz should be check for coordinates/scenery and waiting should be considered, are Sup and surfing clumpable? Making assumong that Kid/Family means beachgoing? Swimming but went for mega fauna?
dat <- Ning %>%
  mutate(Activity_other= ifelse(str_detect(Activity_other,"Swim|swim|play|Relax|castles|Chilling|Drinking|Kid|scenery|Waiting|waiting|Beach|Family|relax|whale"), "Beachgoing", Activity_other),
         Activity_other= ifelse(str_detect(Activity_other, "Dog|dog"), "DogWalking",Activity_other),
         Activity_other = ifelse(str_detect(Activity_other, "Kayak|kayak"), "RowSport", Activity_other),
         Activity_other = ifelse(str_detect(Activity_other, "walk|Walk"), "Walking", Activity_other),
         Activity_other = ifelse(str_detect(Activity_other, "Whale|turtle|Mega"), "Megafauna", Activity_other),
         Activity_other = ifelse(str_detect(Activity_other, "Sand|glass|Rockpooling|Quad|Bird|shells"), "Other", Activity_other),
         Activity_other = ifelse(str_detect(Activity_other, "Wing"), "WindSport", Activity_other),
         Activity_other = ifelse(str_detect(Activity_other, "Skurfing|Sup|Paddle|surf"), "Surfing", Activity_other),
         Activity_other = ifelse(str_detect(Activity_other, "Snork|snork|Tant|trout"), "Snorkeling", Activity_other),
         Activity_other = ifelse(str_detect(Activity_other, "Explore|explore|weather|look"), "Explore", Activity_other),
         Activity_other = ifelse(str_detect(Activity_other, "Just briefly |With group of fishers"), "", Activity_other),
         Activity = ifelse(str_detect(Activity, "Relaxing"), "Beachgoing", Activity),
         Activity = ifelse(str_detect(Activity, "Kite surfing "), "WindSport", Activity),
         Activity = ifelse(str_detect(Activity, "Snork"), "Snorkeling", Activity),
         Activity = ifelse(str_detect(Activity_other,"Beachgoing|DogWalking|RowSport|Walking|Mega|Other|Wind|Surfing|Snork|Explore"), Activity_other, Activity),
         Activity = ifelse(Year == "2015", "Fishing", Activity),
         Activity = ifelse(Year == "2016", "Fishing", Activity),
         Activity = ifelse(Activity == "", "Fishing", Activity),
         FishingType = ifelse(str_detect(FishingType, "Demersal|Bottom"), "Demersal", FishingType),
         UseLong = as.numeric(UseLong),
         UseLat = as.numeric(UseLat)) %>%
  filter(!is.na(UseLong), UseLong != "", !is.na(UseLat), UseLat != "") %>%
  mutate(ActivityType = ifelse(str_detect(Activity, "Fishing"), "Extractive", "Non-Extractive")) %>%
  mutate(Year = as.factor(Year))
  
exdat <- dat %>% 
  filter(Activity == "Fishing") 

unique(exdat$Activity)

nexdat <- dat %>% 
  filter(Activity != "Fishing")

unique(nexdat$Activity)

# library(package)
# ifelse(str_detect(col, ""), T, F)
# dat
# Histogram of activities
Ac <- dat %>% 
  group_by(Activity) %>%   
  mutate(count_name_occurr = n())

Ac %>% ggplot(
  aes(x=reorder(Activity,-count_name_occurr))) +
  geom_bar(stat="count", fill = "Orange") +
  labs(x = "Activity", y = "Frequency")

Ac %>%
  count(Activity)

dat %>% 
  count(Activity) %>%
  count(n_distinct(Activity))

# Histogram of extractive vs non extractive
 ggplot(dat) +
  aes(x = ActivityType) +
  geom_bar(fill = "orange") +
   labs(x = "Activity Type", y = "Frequency")
 
 dat %>% 
   count(ActivityType)

# spatial plots of activities
ggplot(dat) +
  aes(x = UseLong, y = UseLat, color = Activity) +
  geom_point()

sdat <- st_as_sf(dat, coords = c("UseLong", "UseLat"), ## This wont worj if there are blanks in data set so  filtered
                  crs = "+proj=longlat +datum=WGS84 +no_defs")

sdat

plot(sdat["Activity"]) 

tm_shape(sdat) +
  tm_dots(col = "Activity",
          title = "Activities")

#exdat
# Hist of fihsing type
FT <- exdat %>% 
  group_by(FishingType) %>%   
  mutate(count_name_occurr = n()) %>%
  filter(!is.na(FishingType), FishingType != "") 

FT %>% ggplot(
  aes(x=reorder(FishingType,-count_name_occurr))) +
  geom_bar(stat='count', fill = "Orange") +
  labs(x = "Fishing Type", y = "Frequency")



 FT %>% 
  ggplot(aes(x=reorder(FishingType,-count_name_occurr), fill = Year)) +
  geom_bar(position = "dodge") +
  labs(x = "Fishing Type", y = "Frequency")
 
# Freq of DP with each fishing type  -> scale to 6000?? need to get overall percentage per group

# FT %>% ggplot(
#   aes(x=reorder(FishingType,-count_name_occurr), y = perDP)) +
#   geom_col(color = "Orange", fill = "Orange") +
#   labs(x = "Fishing Type", y = "Percentage Depredated") +
#  scale_y_continuous(labels = scales::percent)

summary(FT$perDP)

FT %>%
  count(n_distinct(FishingType))

# Hist of nDP

ggplot(exdat) +
  aes(x = nDP) +
  geom_histogram(fill = "Orange") +
  labs(x = "Depredation", y = "Frequency")

ggplot(exdat) +
  aes(x = nDP) +
  geom_histogram(fill = "Orange") +
  labs(x = "Depredation", y = "Frequency")

which(exdat$nDP > 15) # 8 datra points
which(exdat$nDP == 50 )

a <- exdat %>%
  filter(nDP < 15) 

  ggplot(a) +
  aes(x = nDP) +
  geom_histogram(fill = "Orange") +
  labs(x = "Depredation", y = "Frequency")


# Hist of perDP
ggplot(exdat) +
  aes(x = perDP) +
  geom_histogram(fill = "Orange") +
  labs(x = "Percentage Depredated", y = "Frequency")
  
# per DP vs Year -> need to be summed for each year 
# 
b <- exdat %>%
  group_by(Year) %>%
  summarise(THooked = cumsum(nHooked),
            TDP = cumsum(nDP),
            TperDP = TDP/THooked*100)

b

ggplot(exdat) +
  aes(x = Year, y = perDP) +
  geom_col(colour = "Orange", fill = "Orange") +
  labs(y = "Percentage Depredated")

# Spatial plot  of fishing
ggplot(exdat) +
  aes(x = UseLong, y = UseLat, color = perDP) +
  geom_point()

sexdat <- st_as_sf(exdat, coords = c("UseLong", "UseLat"), ## This wont worj if there are blanks in data set so  filtered
                  crs = "+proj=longlat +datum=WGS84 +no_defs")

sexdat

plot(sexdat["perDP"])

tm_shape(sexdat) +
  tm_dots(title = "Fishing Distribution")

# Spatial plor of fishing with percentage depredation
tm_shape(sexdat) +
  tm_dots(col = "perDP",
          palette = "Oranges",
          title = "Percentage Depredated")

# Spatail plot of fishing with percent of depredation for 2015/16
jexdat <- dat %>%
  filter(Year == "2015") 

jexdat %>%
  count(Year)

sjexdat <- st_as_sf(jexdat, coords = c("UseLong", "UseLat"), ## This wont worj if there are blanks in data set so  filtered
                  crs = "+proj=longlat +datum=WGS84 +no_defs")
tm_shape(sjexdat) +
  tm_dots(col = "perDP",
          palette = "Blues",
          title = "Percentage Depredated")

# Spatail plot of fishing with percent of depredation for 2020/21
 
exdat20 <- exdat %>%
  filter(Year > 2016)

exdat20 %>%
  count(Year) 

sexdat20 <- st_as_sf(exdat20, coords = c("UseLong", "UseLat"), ## This wont worj if there are blanks in data set so  filtered
                  crs = "+proj=longlat +datum=WGS84 +no_defs")

tm_shape(sexdat20) +
  tm_dots(col = "perDP",
          palette = "Purples",
          title = "Percentage Depredated")


#nexdat
ggplot(nexdat) +
  aes(x = UseLong, y = UseLat, color = Activity) +
  geom_point()

snexdat <- st_as_sf(nexdat, coords = c("UseLong", "UseLat"), ## This wont worj if there are blanks in data set so  filtered
                  crs = "+proj=longlat +datum=WGS84 +no_defs")

snexdat

plot(snexdat["Activity"])

tm_shape(snexdat) +
  tm_dots(col = "Activity",
          title = "Activities")
names(dat)

WA <- "/Users/23088313/Documents/Spatial/shp/waCoast.shp"
st_read(WA)

WA <- st_read(s.dir, "waCoast", sep ="/")

WA <- st_read("~/Documents/Spatial/shp/waCoast.shp")

WA <- st_read("../../Spatial/shp/waCoast.shp")

gb <- readOGR(paste(s.dir, "waCoast.shp",sep='/'))

summary(Ning$nDP)
```

